### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by SensorsIot** [Arielhh/ESP32-Radio-Internet-With-TouchScreen-Display#1]
Do you plan to publish the source code? And is it in the Arduino IDE or the IDF?

**Comment by MrSniffer** [comment]
I'd learn a lot from studying your source code. And I'd like to port the project to a T-Deck, which I happen to have.

**Comment by whashburn** [comment]
This is a wonderful project.  Will you be willing to share the source code.  If so, we would greatly appreciate it.

**Comment by m-kareem** [comment]
looking forward for sharing the source code

**Comment by MicroMkr** [comment]
Thanks for watching my videos and for reaching out. The code was written using the Arduino IDE. Unfortunately, I don't feel comfortable sharing the code yet as I am still working on improving it. Feel free to use the binary code, it is fully functional.

**Comment by whashburn** [comment]
Hi
Thanks for responding so quickly.  And thank you for sharing your work.  I totally respect your desire to protect your code, and not share it (until you are confident and proud of it).  
 
I am an avid fan of internet radio.  I have had internet radios in my home for more than ten years (made by Grace Digital  Grace Digital Internet Radio – gracedigital <https://gracedigital.com/>  ).  Although I am in the US, my favorite stations are Classic FM (UK), and several other classic music stations.  It will be nice to have a unit I can move from room to room.  It will even be fun designing and printing a case.  Although I must say that Lilygo did not do anything with the design of the T-Display and T-Display touch to make it easy to design a simple mount.
 
Continued success with your designs.
 
Best Regards
Hank

**Comment by MicroMkr** [comment]
Hi Hank,
Thanks for sharing your experience with Internet Radios. Also thanks for understanding.
Your Grace Digital Internet Radio looks of very good quality. 
It should be possible to play any Internet station on the Radio demonstrated here.
However, I have to admit that this module doesn't have the best WiFi reception. 
If you wish to build it yourself please use the binary files provided here. 
Also, if you would like to get my 3D box design I will be able to send it to you but please note that it will require some slicer fiddling required for creating the speaker mesh.  

Ariel

**Comment by whashburn** [comment]
Hi Ariel,
If you do not mind I would really like to see the 3D Box design you are willing to share – merely to learn a good way to securely mount the T-Display behind a front panel.  I have looked at and downloaded several STL’s from Printables and Thingverse and all the designs I came across are boxes just big enough to hold the display.  Even Volos Projects doesn’t have a case for generic mounting the display with additional components.

**Comment by MicroMkr** [comment]
> Hi Hank,
I uploaded the STL files of the box.

**Comment by whashburn** [comment]
Thank you Ariel.
 
I like the case.  The clips are very well placed.  One question: how are you holding the T-Display in place?  I was thinking of adding header pins to the Touch, and cutting a protoboard to fit in a box (such as yours), and putting matching sockets on the protoboard.  It would then be straight forward to print mounting posts inside of the box, and screw the protoboard to the mounting posts.   Did you do something similar? 
 
Thanks.
 
Hank

**Comment by MicroMkr** [comment]
A bit of hot glue is doing the job.

**Comment by whashburn** [comment]
AHHHHH  <grin>
 
Hope you have a good weekend.  I

**Comment by whashburn** [comment]
Hello Ariel,
I hope you had a good week.  I apologize for interrupting your weekend.
 
I like your graphic design and interface very much. Nice job.  And adding the ability to add stations was done well.  One problem, that is not your responsibility, is that several of the stations (I wish to listen to) often require clicking a PLAY link after connecting the web site. Oh well.
 
I finally received my order for an I2S amplifier and noticed that the audio for Helios was going on and off in about a one second period.  I scoped the clock, L+R, and Data channels and noticed that during periods of silence the Data channel (the topmost cyan trace) comprised spikes, instead of a traditional trace of a binary data signal.  For reference, the magenta trace is the clock, and the yellow trace is the L+R, and when I took this snapshot, the I2S amplifier is not connected to the Lilygo, so I am not seeing the I2S chip loading down the Lilygo. 
 

 
 
If you have a moment, would you answer the following questions for me?
1.	When you were coding and debugging, did you come across the on/off of the Data behavior?  I know you mentioned that the Wi-Fi section is not great.  Do you think this is the reason?  I even connected an external strip antenna and that did change the behavior.  I have three or four other Lilygo Display, and Display Touch in use and I have not notice connectivity problems, although this is the first project that requires a continuous data stream.  My Touch was about 5 feet from the router when I took this screen grab.
2.	Are you using HTTP or UDP?
3.	Although you included all of the pin #DEFINES, am I correct assuming that the only three pins we need to concern ourselves with at the Clock, L+R, and Data?
 
May I suggest adding two notes to your readme:
*	In the screen grab you provided to flash the bin files, please explain that the boot_app0.bin file is included with the Lilygo flash tool in the bin directory.
*	An I2S amplifier is required for this project.  Consult the I2S data sheet how learn how to activate the (L+R)/2 or stereo signal.  The MAX98357 (if it really is that part) I am using, requires connecting the SD pin of the chip to a GPIO, or adding three resistors to build a voltage divider and load to the SD pin to get L+R signal.
 
 
Many thanks 😊
 
Hank

**Comment by MicroMkr** [comment]
Hi, Hank, can you give me an example of a station you need to press the play button in order to play it?
Can you send me a snapshot of that on/off Data behavior you are describing?  When I mentioned the weak wifi of the Lilygo I was referring to the reception distance.  
I am using HTTP.
Regarding the pins yes only need to connect 3 pins. of course, in addition, you need to connect VCC and Ground. If you are using the MAX98357a chip it will be very easy as it allines with the holes on the Liliygo Touch. so you can use headers for connection (no need to use wires except for the speaker). 
Regarding the SD pin, you can leave it unconnected. Refer to that article: https://dronebotworkshop.com/esp32-i2s/ for an explanation. Anyway, the signal I am sending from the Liligo is Mono. If you wish to have a stereo sound please wait for next week and I will upload an additional version that supports stereo sound.  Anyway, the MAX98357a is a mono amp, if you wish to use it in stereo configuration you will need to use a two-chip configuration. The sound of the MAX98357a is reasonable but I prefer the PCM5102A along with an additional amplifier module or external amplifier.  The PCM5102A DAC is much better than the one used in the MAX chip. 
i will add your comments to the GitHub page hopefully next week.

**Comment by whashburn** [comment]
Hi Ariel,
This is very exciting – I am definitely looking forward to the Stereo version.  And thank you very much for the suggestion to use the PCM5102A.  The MAX’s were an 3 for US$10 on Amazon.  There was no engineering reason I selected them.  And as I alluded to in my earlier email, there are no markings on the chip so I really wonder what they are.
 
I don’t mean to overwhelm you with stations that require clicking a link to listen, these are a few of the stations I often listen to.  If it is any help, I often listen these stations using Google Home (Google Next) smart speaker.  I do not know the API that the Google programming teams use, but I can imagine it is a difficult task for the multitude of internet radio providers. 
 
Off topic:  I have written two weather displays loosely based on Volos Projects speedometer.  They are both based on the Lilygo T-Display S3 and both display two graphs at the same time.   One uses the SHT40 (from Adafruit) to display temp and humid in the room.  The other displays the temp/humid/barometric of one or more cities.  If you are interested, I am more than happy to send you the source code for both projects – as a thank you.  Is there are way for me to send you the code to your private email?
 
Hank 
 
 

Classic FM uses TuneIn
 
 

Audacy
 
 

These are public stations in the New York/New Jersey area and do not use a third party
 
 

Klara uses myTuner
 

Radio.net carries many stations, including Klara

**Comment by MicroMkr** [comment]
Hi Hunk,
Please send me your email and I will be happy to send you an explanation on how to get the address of these stations that you like listening to.

**Comment by whashburn** [comment]
***@***.***

**Comment by MicroMkr** [comment]
It is not possible to see the email address, I see stars instead. I guess it is due to privacy protection :)

**Comment by whashburn** [comment]
Hank (dot) qbgroup (at) gmail (dot) com

**Comment by MicroMkr** [comment]
Hi Hank,
I believe this is a link to one of the stations: Classic FM UK, https://media-the.musicradio.com/ClassicFM 
Try using  one of the following websites https://streamurl.link/ or https://radio.garden/visit/guantanamo/fzmjbtI8
You can find on YouTube instructions on how to get the IP address without the need to press the play button

**Comment by MicroMkr** [comment]
> Do you plan to publish the source code? And is it in the Arduino IDE or the IDF?
Hi Andreas,
I like your youtube channel. 
If you wish to build my radio let me know and i will send you an activation key :)
I will be happy to hear your opinion
You can download the bin file from my repository: https://1drv.ms/f/s!AtdSBdR1Gbo4emcDm8-6_pUZIXc?e=i8rn3N
